# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=250)),
                ('app_name', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('api_key', models.CharField(max_length=250)),
                ('api_secret', models.CharField(max_length=250)),
                ('access_token', models.CharField(max_length=250)),
                ('access_token_secret', models.CharField(max_length=250)),
            ],
        ),
    ]
